const FETCHING_START_ACTION = 'FETCHING_START_ACTION';
const FETCHING_END_ACTION = 'FETCHING_END_ACTION';
const FETCHED_FEATURES = 'FETCHED_FEATURES';
const OPEN_DELETE_DIALOG = 'OPEN_DELETE_DIALOG';
const CLOSE_DELETE_DIALOG = 'CLOSE_DELETE_DIALOG';
const OPEN_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG';
const CLOSE_EDIT_DIALOG= 'CLOSE_EDIT_DIALOG';
const OPEN_EDIT_DIALOG = 'OPEN_EDIT_DIALOG';
const DELETE_FEATURE = 'DELETE_FEATURE';
const FEATURE_REMOVED = 'FEATURE_REMOVED';
const UPDATE_FEATURE = 'UPDATE_FEATURE';
const CREATED_FEATURE = 'CREATED_FEATURE';
const SEND_SNACK_MESSAGE = 'SEND_SNACK_MESSAGE';
const CLEAR_SNACK_MESSAGE = 'CLEAR_SNACK_MESSAGE';
const GOOGLE_AUTH= 'GOOGLE_AUTH';

export {
    FETCHING_START_ACTION,
    FETCHING_END_ACTION,
    FETCHED_FEATURES,
    OPEN_DELETE_DIALOG,
    CLOSE_DELETE_DIALOG,
    DELETE_FEATURE,
    FEATURE_REMOVED,
    OPEN_CREATE_DIALOG,
    CLOSE_CREATE_DIALOG,
    UPDATE_FEATURE,
    CLOSE_EDIT_DIALOG,
    OPEN_EDIT_DIALOG,
    CREATED_FEATURE,
    SEND_SNACK_MESSAGE,
    CLEAR_SNACK_MESSAGE,
    GOOGLE_AUTH
}