const FETCHING_START_ACTION = 'FETCHING_START_ACTION';
const FETCHING_END_ACTION = 'FETCHING_END_ACTION';
const FETCHED_FEATURES = 'FETCHED_FEATURES';
const FETCHING_ENRICHED_DATA_START = 'FETCHING_ENRICHED_DATA_START';
const FETCHING_ENRICHED_DATA_END = 'FETCHING_ENRICHED_DATA_END';
const FETCHED_ENRICHED_DATA = 'FETCHED_ENRICHED_DATA';
const OPEN_DELETE_DIALOG = 'OPEN_DELETE_DIALOG';
const CLOSE_DELETE_DIALOG = 'CLOSE_DELETE_DIALOG';
const OPEN_CREATE_DIALOG = 'OPEN_CREATE_DIALOG';
const CLOSE_CREATE_DIALOG = 'CLOSE_CREATE_DIALOG';
const OPEN_ENRICHED_DIALOG = 'OPEN_ENRICHED_DIALOG';
const CLOSE_ENRICHED_DIALOG = 'CLOSE_ENRICHED_DIALOG';
const CLOSE_EDIT_DIALOG = 'CLOSE_EDIT_DIALOG';
const OPEN_EDIT_DIALOG = 'OPEN_EDIT_DIALOG';
const DELETE_FEATURE = 'DELETE_FEATURE';
const FEATURE_REMOVED = 'FEATURE_REMOVED';
const UPDATE_FEATURE = 'UPDATE_FEATURE';
const SAVE_UPDATED_FEATURE = 'SAVE_UPDATED_FEATURE';
const CREATED_FEATURE = 'CREATED_FEATURE';
const SEND_SNACK_MESSAGE = 'SEND_SNACK_MESSAGE';
const CLEAR_SNACK_MESSAGE = 'CLEAR_SNACK_MESSAGE';
const GOOGLE_AUTH = 'GOOGLE_AUTH';

export {
    FETCHING_START_ACTION,
    FETCHING_END_ACTION,
    FETCHED_FEATURES,
    FETCHING_ENRICHED_DATA_START,
    FETCHING_ENRICHED_DATA_END,
    FETCHED_ENRICHED_DATA,
    SAVE_UPDATED_FEATURE,
    UPDATE_FEATURE,
    OPEN_DELETE_DIALOG,
    CLOSE_DELETE_DIALOG,
    DELETE_FEATURE,
    FEATURE_REMOVED,
    OPEN_CREATE_DIALOG,
    CLOSE_CREATE_DIALOG,
    CLOSE_EDIT_DIALOG,
    OPEN_EDIT_DIALOG,
    CREATED_FEATURE,
    SEND_SNACK_MESSAGE,
    CLEAR_SNACK_MESSAGE,
    GOOGLE_AUTH,
    OPEN_ENRICHED_DIALOG,
    CLOSE_ENRICHED_DIALOG,
}