const FETCHING_START_ACTION = "FETCHING_START_ACTION"
const FETCHING_END_ACTION = "FETCHING_END_ACTION"
const FETCHED_FEATURES = "FETCHED_FEATURES"

export {
    FETCHING_START_ACTION,
    FETCHING_END_ACTION,
    FETCHED_FEATURES
}